/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author user
 */
public class FrmAdministrador extends javax.swing.JDialog {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bibliotecario = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_agregarBibli = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_agregarBibli1 = new javax.swing.JButton();
        btn_agregarBibli2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de Administrador");
        setIconImage(UtilidadesComponente.obtenerIcono());
        setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO ADMINISTRADOR");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 40, 332, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lista de Bibliotecario");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 90, 121, 17);

        tbl_bibliotecario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_bibliotecario);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 118, 430, 108);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 250, 410, 13);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Lista de Usuario");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 270, 95, 17);

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_usuario);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 294, 430, 106);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 1, 450, 450);

        jPanel3.setLayout(null);

        btn_agregarBibli.setText("Agregar");
        jPanel3.add(btn_agregarBibli);
        btn_agregarBibli.setBounds(20, 280, 110, 30);

        jButton1.setText("SALIR");
        jPanel3.add(jButton1);
        jButton1.setBounds(20, 400, 110, 30);

        btn_agregarBibli1.setText("Agregar");
        jPanel3.add(btn_agregarBibli1);
        btn_agregarBibli1.setBounds(20, 180, 110, 30);

        btn_agregarBibli2.setText("Agregar");
        jPanel3.add(btn_agregarBibli2);
        btn_agregarBibli2.setBounds(20, 230, 110, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 0, 150, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 450);

        setSize(new java.awt.Dimension(616, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAdministrador dialog = new FrmAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarBibli;
    private javax.swing.JButton btn_agregarBibli1;
    private javax.swing.JButton btn_agregarBibli2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_bibliotecario;
    private javax.swing.JTable tbl_usuario;
    // End of variables declaration//GEN-END:variables
}
