/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author user
 */
public class FrmAdministrador extends javax.swing.JDialog {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedSelector21 = new org.edisoncor.gui.tabbedPane.TabbedSelector2();
        jPanel2 = new javax.swing.JPanel();
        panelReflect1 = new org.edisoncor.gui.panel.PanelReflect();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAeroLeft3 = new org.edisoncor.gui.button.ButtonAeroLeft();
        buttonAeroRight7 = new org.edisoncor.gui.button.ButtonAeroRight();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel6 = new javax.swing.JLabel();
        textFieldRound1 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel12 = new javax.swing.JLabel();
        textFieldRound2 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel13 = new javax.swing.JLabel();
        textFieldRound3 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        textFieldRound4 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        textFieldRound5 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        comboBoxRectIcon1 = new org.edisoncor.gui.comboBox.ComboBoxRectIcon();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel17 = new javax.swing.JLabel();
        textFieldRound6 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel18 = new javax.swing.JLabel();
        passwordFieldRound1 = new org.edisoncor.gui.passwordField.PasswordFieldRound();
        buttonIpod1 = new org.edisoncor.gui.button.ButtonIpod();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelReflect5 = new org.edisoncor.gui.panel.PanelReflect();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonRect1 = new org.edisoncor.gui.button.ButtonRect();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        labelCustom2 = new org.edisoncor.gui.label.LabelCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de Administrador");
        setIconImage(UtilidadesComponente.obtenerIcono());
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tabbedSelector21.setBackground(new java.awt.Color(0, 102, 102));
        tabbedSelector21.setColorBackGround(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        panelReflect1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelReflect1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Bibliotecarios");
        panelReflect1.add(jLabel1);
        jLabel1.setBounds(260, 30, 120, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelReflect1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 550, 250);

        buttonAeroLeft3.setBackground(new java.awt.Color(0, 255, 255));
        buttonAeroLeft3.setText("Editar");
        panelReflect1.add(buttonAeroLeft3);
        buttonAeroLeft3.setBounds(190, 360, 110, 25);

        buttonAeroRight7.setBackground(new java.awt.Color(0, 204, 204));
        buttonAeroRight7.setText("Dar de baja");
        panelReflect1.add(buttonAeroRight7);
        buttonAeroRight7.setBounds(310, 360, 120, 25);

        jPanel2.add(panelReflect1);
        panelReflect1.setBounds(0, 0, 600, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ue_biblioteca-mediateca-icono.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(360, 160, 510, 330);

        tabbedSelector21.addTab("Bibliotecarios", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);
        jPanel3.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 0, 0);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(300, 70, 70, 20);
        jPanel3.add(textFieldRound1);
        textFieldRound1.setBounds(70, 120, 520, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 20, 70, 20);
        jPanel3.add(textFieldRound2);
        textFieldRound2.setBounds(260, 220, 160, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apellidos:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(300, 20, 70, 20);
        jPanel3.add(textFieldRound3);
        textFieldRound3.setBounds(370, 20, 220, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Seccion:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(200, 180, 70, 20);
        jPanel3.add(textFieldRound4);
        textFieldRound4.setBounds(70, 20, 220, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cedula:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 70, 70, 20);
        jPanel3.add(textFieldRound5);
        textFieldRound5.setBounds(70, 70, 220, 30);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Contraseña:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(180, 260, 100, 20);
        jPanel3.add(comboBoxRectIcon1);
        comboBoxRectIcon1.setBounds(260, 180, 160, 20);
        jPanel3.add(panelCurves2);
        panelCurves2.setBounds(0, 0, 120, 0);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Correo:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 120, 70, 20);

        textFieldRound6.setText("textFieldRound1");
        jPanel3.add(textFieldRound6);
        textFieldRound6.setBounds(370, 70, 220, 30);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Usuario:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(200, 220, 70, 20);
        jPanel3.add(passwordFieldRound1);
        passwordFieldRound1.setBounds(260, 260, 160, 30);

        buttonIpod1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonIpod1.setText("Registrar");
        buttonIpod1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel3.add(buttonIpod1);
        buttonIpod1.setBounds(290, 330, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ue_biblioteca-mediateca-icono.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 160, 510, 330);

        tabbedSelector21.addTab("Añadir Bibliotecario", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(null);

        panelReflect5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelReflect5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Buscar :");
        panelReflect5.add(jLabel3);
        jLabel3.setBounds(10, 20, 90, 20);
        panelReflect5.add(jTextField2);
        jTextField2.setBounds(70, 20, 280, 20);

        jRadioButton1.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Profesor");
        panelReflect5.add(jRadioButton1);
        jRadioButton1.setBounds(380, 5, 90, 50);

        jRadioButton2.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Alumno");
        panelReflect5.add(jRadioButton2);
        jRadioButton2.setBounds(470, 10, 100, 40);

        jPanel4.add(panelReflect5);
        panelReflect5.setBounds(10, 10, 590, 70);

        buttonRect1.setBackground(new java.awt.Color(255, 51, 51));
        buttonRect1.setText("Dar de baja");
        jPanel4.add(buttonRect1);
        buttonRect1.setBounds(250, 360, 111, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 90, 590, 250);

        tabbedSelector21.addTab("Usuarios", jPanel4);

        jPanel1.add(tabbedSelector21);
        tabbedSelector21.setBounds(10, 50, 750, 430);

        labelCustom2.setBackground(new java.awt.Color(0, 102, 102));
        labelCustom2.setText("Administrador");
        jPanel1.add(labelCustom2);
        labelCustom2.setBounds(0, 0, 890, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 760, 480);

        setSize(new java.awt.Dimension(762, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAdministrador dialog = new FrmAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAeroLeft buttonAeroLeft3;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight7;
    private org.edisoncor.gui.button.ButtonIpod buttonIpod1;
    private org.edisoncor.gui.button.ButtonRect buttonRect1;
    private org.edisoncor.gui.comboBox.ComboBoxRectIcon comboBoxRectIcon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField2;
    private org.edisoncor.gui.label.LabelCustom labelCustom2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect1;
    private org.edisoncor.gui.panel.PanelReflect panelReflect5;
    private org.edisoncor.gui.passwordField.PasswordFieldRound passwordFieldRound1;
    private org.edisoncor.gui.tabbedPane.TabbedSelector2 tabbedSelector21;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound1;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound2;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound3;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound4;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound5;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound6;
    // End of variables declaration//GEN-END:variables
}
