/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author user
 */
public class FrmUsuario extends javax.swing.JDialog {

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedSelector21 = new org.edisoncor.gui.tabbedPane.TabbedSelector2();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbxTipoBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBusquedaAvanzada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven3 = new org.edisoncor.gui.button.ButtonSeven();
        jLabel4 = new javax.swing.JLabel();
        panelCurves5 = new org.edisoncor.gui.panel.PanelCurves();
        jPanel7 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        panelCurves4 = new org.edisoncor.gui.panel.PanelCurves();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        panelCurves3 = new org.edisoncor.gui.panel.PanelCurves();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        buttonSeven2 = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de Usuario");
        setIconImage(UtilidadesComponente.obtenerIcono());
        getContentPane().setLayout(null);

        tabbedSelector21.setBackground(new java.awt.Color(0, 102, 102));
        tabbedSelector21.setColorBackGround(new java.awt.Color(0, 102, 102));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(84, 125, 138));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Documentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(230, 231, 233))); // NOI18N
        jPanel2.setLayout(null);

        cbxTipoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Título", "Autor" }));
        jPanel2.add(cbxTipoBuscar);
        cbxTipoBuscar.setBounds(30, 30, 70, 20);
        jPanel2.add(txtBuscar);
        txtBuscar.setBounds(110, 30, 390, 20);

        btnBusquedaAvanzada.setForeground(new java.awt.Color(230, 231, 233));
        btnBusquedaAvanzada.setText("Búsqueda Avanzada");
        btnBusquedaAvanzada.setBorder(null);
        btnBusquedaAvanzada.setBorderPainted(false);
        btnBusquedaAvanzada.setContentAreaFilled(false);
        jPanel2.add(btnBusquedaAvanzada);
        btnBusquedaAvanzada.setBounds(510, 30, 110, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Resultados de Busqueda");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(270, 60, 140, 14);

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 640, 250);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 350, 610, 10);

        buttonSeven1.setText("Solicitar");
        jPanel2.add(buttonSeven1);
        buttonSeven1.setBounds(390, 360, 150, 30);

        buttonSeven3.setText("Ver informacion");
        jPanel2.add(buttonSeven3);
        buttonSeven3.setBounds(130, 360, 180, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ue_biblioteca-mediateca-icono.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 150, 510, 330);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(10, 10, 670, 400);
        jPanel6.add(panelCurves5);
        panelCurves5.setBounds(0, 0, 690, 430);

        tabbedSelector21.addTab("Documentos", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(null);
        jPanel7.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 0, 0);
        jPanel7.add(panelCurves2);
        panelCurves2.setBounds(0, 0, 120, 0);

        jPanel3.setBackground(new java.awt.Color(85, 111, 122));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Préstamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(230, 231, 233))); // NOI18N
        jPanel3.setLayout(null);

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPrestamos);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 30, 630, 330);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ue_biblioteca-mediateca-icono.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(440, 160, 510, 330);

        jPanel7.add(jPanel3);
        jPanel3.setBounds(10, 10, 670, 400);
        jPanel7.add(panelCurves4);
        panelCurves4.setBounds(0, 0, 690, 430);

        tabbedSelector21.addTab("Prestamos", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(121, 128, 134));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Multas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(230, 231, 233))); // NOI18N
        jPanel4.setLayout(null);

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMultas);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 630, 350);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ue_biblioteca-mediateca-icono.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(410, 150, 510, 330);

        jPanel8.add(jPanel4);
        jPanel4.setBounds(10, 10, 670, 400);
        jPanel8.add(panelCurves3);
        panelCurves3.setBounds(-10, -10, 700, 440);

        tabbedSelector21.addTab("Multas", jPanel8);

        getContentPane().add(tabbedSelector21);
        tabbedSelector21.setBounds(0, 50, 800, 440);

        panel1.setForeground(new java.awt.Color(0, 102, 102));
        panel1.setColorPrimario(new java.awt.Color(0, 102, 102));
        panel1.setColorSecundario(new java.awt.Color(0, 204, 204));
        panel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel2.setText("Bienvenido al Sistema biliotecario");
        panel1.add(jLabel2);
        jLabel2.setBounds(220, 0, 380, 50);

        buttonSeven2.setText("Cerrar sesion");
        panel1.add(buttonSeven2);
        buttonSeven2.setBounds(670, 10, 116, 35);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 800, 50);

        setSize(new java.awt.Dimension(817, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmUsuario dialog = new FrmUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaAvanzada;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven2;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven3;
    private javax.swing.JComboBox<String> cbxTipoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves3;
    private org.edisoncor.gui.panel.PanelCurves panelCurves4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves5;
    private org.edisoncor.gui.tabbedPane.TabbedSelector2 tabbedSelector21;
    private javax.swing.JTable tblMultas;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
